import { afterEach, describe, expect, it } from 'vitest'
import { mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { DshTaskExecutor, DurableTaskWorker, SQLiteTaskStore, TaskService, type StoredTask } from '../src/tasks/index.js'
const dirs:string[]=[]
const store=()=>{const d=mkdtempSync(join(tmpdir(),'mesh-task-'));dirs.push(d);return new SQLiteTaskStore(join(d,'tasks.db'),{pollIntervalMs:2})}
afterEach(()=>dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true})))
describe('SQLiteTaskStore',()=>{
 it('persists, deduplicates atomically, CASes, and resumes event cursors',async()=>{const a=store();const t={taskId:'t',status:'queued' as const,createdAt:'2025-01-01T00:00:00Z',updatedAt:'2025-01-01T00:00:00Z',revision:0};const r:StoredTask={task:t,idempotencyKey:'k',requestFingerprint:'f'};expect((await a.admit(r)).deduplicated).toBe(false);expect((await a.admit(r)).deduplicated).toBe(true);const first=await a.events('t');expect(first.events).toHaveLength(1);expect(await a.compareAndSet('t',9,{task:{...t,revision:10}})).toBeUndefined();await a.compareAndSet('t',0,{task:{...t,status:'running',revision:1},events:[{type:'progress',progress:.5}]});const page=await a.events('t',first.cursor);expect(page.events.map(x=>x.type)).toEqual(['snapshot','progress']);a.close();const b=new SQLiteTaskStore(a.filename);expect((await b.get('t'))?.task.status).toBe('running');b.close()})
 it('fences leases, recovers expired runs, and executes queued work once',async()=>{let now=0;const s=store();const admission={task:{taskId:'x',status:'running' as const,createdAt:new Date(0).toISOString(),updatedAt:new Date(0).toISOString(),revision:0},idempotencyKey:'x',requestFingerprint:'x'};await s.admit(admission);const lease=s.acquireLease('x','a',10000,'one')!;expect(s.acquireLease('x','b',10000,'two')).toBeUndefined();expect(s.releaseLease('x','a','wrong')).toBe(false);s.releaseLease('x','a',lease.token);expect((await s.recover())[0]?.status).toBe('queued');let calls=0;const svc=new TaskService(s,{async execute(){calls++;return 'ok'}},{autoStart:false});const worker=new DurableTaskWorker(s,svc,{owner:'w'});await Promise.all([worker.runOnce(),worker.runOnce()]);expect(calls).toBe(1);expect((await s.get('x'))?.task.status).toBe('succeeded');s.close()})
})
describe('DshTaskExecutor',()=>{it('runs and disposes a cleanroom one-shot subagent',async()=>{let disposed=0,request:any;const executor=new DshTaskExecutor({parent:{},provider:'p',subagents:{async start(_p,r){request=r;return{result:Promise.resolve({stopReason:'completed',output:[{type:'text',text:'answer'}]}),dispose(){disposed++}}}}});const out=await executor.execute({taskId:'t',status:'running',createdAt:'',updatedAt:'',input:{q:1}}, {signal:new AbortController().signal,progress:async()=>{},artifact:async()=>{},log:async()=>{}});expect(request.prompt[0].text).toBe('{"q":1}');expect(out).toEqual({output:'answer'});expect(disposed).toBe(1)})
 it('bridges Prime sessions and records their durable id',async()=>{const logs:unknown[]=[];const executor=new DshTaskExecutor({prime:{async start(){return{sessionId:'s1',result:Promise.resolve({ok:true})}}}});expect(await executor.execute({taskId:'t',status:'running',createdAt:'',updatedAt:'',input:'go'},{signal:new AbortController().signal,progress:async()=>{},artifact:async()=>{},log:async x=>{logs.push(x)}})).toEqual({output:{ok:true}});expect(logs).toEqual([{primeSessionId:'s1'}])})})
